my_dictionary/authentication/urls.py
from django.urls import path

from .views import (ChangePassword, ChangePasswordDone, LoginUser, MyProfile,
                    MyProfileEdit, PasswordResetComplete, PasswordResetConfirm,
                    PasswordResetDone, RegisterUser, ResetPassword,
                    logout_user)

urlpatterns = [
    path("login", LoginUser.as_view(), name="login"),
    path("register", RegisterUser.as_view(), name="register"),
    path("logout", logout_user, name="logout"),
    path("reset_password", ResetPassword.as_view(), name="reset_password"),
    path(
        "reset_password/<uidb64>/<token>/",
        PasswordResetConfirm.as_view(),
        name="password_reset_confirm",
    ),
    path("reset/done/", PasswordResetDone.as_view(), name="password_reset_done"),
    path(
        "reset/complete/",
        PasswordResetComplete.as_view(),
        name="password_reset_complete",
    ),
    path("change_password", ChangePassword.as_view(), name="password_change"),
    path(
        "change_password/done/",
        ChangePasswordDone.as_view(),
        name="password_change_done",
    ),
    path("my_pfofile", MyProfile.as_view(), name="my_profile"),
    path("my_pfofile/edit", MyProfileEdit.as_view(), name="my_profile_edit"),
]

my_dictionary/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path("tinymce/", include("tinymce.urls")),
    path("admin/", admin.site.urls),
    path("", include("authentication.urls")),
    path("", include("dictionary.urls")),
    path("", include("articles.urls")),
    path("", include("diary.urls")),
    path("", include("feedback.urls")),
    path("", include("common.urls")),
    path("", include("text_books.urls")),
    path("", include("reader.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    re_path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = "common.views.page_not_found_view"
handler500 = "common.views.server_error"

if not settings.DEBUG:
    urlpatterns += (
        re_path(
            r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}
        ),
    )

my_dictionary/diary/urls.py
from django.urls import path

from diary.views import DeleteDay, EditDay, MyDiary, NewDay, ShowDay

urlpatterns = [
    path("new_day", NewDay.as_view(), name="new_day"),
    path("my_diary", MyDiary.as_view(), name="my_diary"),
    path("my_diary/<int:day>", ShowDay.as_view(), name="concrete_day"),
    path("my_diary/<int:day>/edit", EditDay.as_view(), name="edit_day"),
    path("my_diary/<int:day>/delete", DeleteDay.as_view(), name="delete_day"),
]

my_dictionary/authentication/models.py
import os

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    GENDER = (("M", "мужской"), ("F", "женский"))

    def image_upload_to(self, instance=None):
        if instance:
            return os.path.join("users", str(self.pk), instance)
        return None

    gender = models.CharField(max_length=1, choices=GENDER, blank=True)
    avatar = models.ImageField(upload_to=image_upload_to, blank=True)
    about_me = models.TextField(blank=True)
    language_learned = models.ForeignKey(
        "dictionary.language", on_delete=models.PROTECT, default=1
    )

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

my_dictionary/authentication/forms.py
from django import forms
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       PasswordResetForm, SetPasswordForm,
                                       UserChangeForm, UserCreationForm)

from .models import User


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(
        label="Логин",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "имя пользователя"}
        ),
    )
    first_name = forms.CharField(
        label="Имя",
        widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "имя"}),
    )
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "пароль1"}
        ),
    )
    password2 = forms.CharField(
        label="Повтор пароля",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "пароль2"}
        ),
    )
    agreement = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"})
    )

    class Meta(UserCreationForm):
        model = User
        fields = ("username", "first_name", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "имя пользователя"}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "пароль"}
        )
    )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "avatar",
            "first_name",
            "last_name",
            "gender",
            "username",
            "email",
            "language_learned",
            "about_me",
        )

        widgets = {
            "avatar": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "gender": forms.Select(attrs={"class": "form-select"}),
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "language_learned": forms.Select(attrs={"class": "form-control"}),
            "about_me": forms.Textarea(attrs={"class": "form-control"}),
        }


class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    new_password1 = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-control"})
    )
    new_password2 = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    class Meta(PasswordChangeForm):
        model = User
        fields = ("old_password", "new_password1", "new_password2")


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(
            attrs={
                "autocomplete": "email",
                "class": "form-control",
                "placeholder": "email",
            }
        ),
    )


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label="New password",
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "пароль1",
            }
        ),
        strip=False,
    )
    new_password2 = forms.CharField(
        label="New password confirmation",
        strip=False,
        widget=forms.PasswordInput(
            attrs={
                "autocomplete": "new-password",
                "class": "form-control",
                "placeholder": "пароль2",
            }
        ),
    )

my_dictionary/authentication/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (LoginView, PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.db import connection
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView
from loguru import logger

from common.mixins.access_mixins import LogoutRequiredMixin
from common.mixins.service_page_mixin import ServicePageMixin
from diary.models import Diary
from dictionary.words_operation import get_dictionary_statistics

from .forms import (CustomPasswordChangeForm, CustomPasswordResetForm,
                    CustomSetPasswordForm, CustomUserChangeForm, LoginUserForm,
                    RegisterUserForm)
from .models import User


class RegisterUser(LogoutRequiredMixin, CreateView):
    form_class = RegisterUserForm
    template_name = "authentication/register.html"
    success_url = reverse_lazy("login")


class LoginUser(LogoutRequiredMixin, LoginView):
    form_class = LoginUserForm
    template_name = "authentication/login.html"


class ChangePassword(LoginRequiredMixin, PasswordChangeView):
    success_url = reverse_lazy("password_change_done")
    template_name = "authentication/change_password.html"
    form_class = CustomPasswordChangeForm


# changing password for authorized user
class ChangePasswordDone(LoginRequiredMixin, ServicePageMixin, PasswordChangeDoneView):
    page_type = "password_change_done"


class ResetPassword(LogoutRequiredMixin, PasswordResetView):
    template_name = "authentication/password_reset_form.html"
    email_template_name = "authentication/password_reset_email.html"
    form_class = CustomPasswordResetForm


class PasswordResetDone(LogoutRequiredMixin, ServicePageMixin, PasswordResetDoneView):
    page_type = "password_reset_done"


class PasswordResetConfirm(LogoutRequiredMixin, PasswordResetConfirmView):
    success_url = reverse_lazy("password_reset_complete")
    template_name = "authentication/password_reset_confirm.html"
    form_class = CustomSetPasswordForm


class PasswordResetComplete(
    LogoutRequiredMixin, ServicePageMixin, PasswordResetCompleteView
):
    page_type = "password_reset_complete"


@logger.catch
@login_required
def logout_user(request):
    logout(request)
    return redirect("login")


class MyProfile(LoginRequiredMixin, TemplateView):
    template_name = "authentication/my_profile.html"

    @logger.catch
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        dictionary_statistics = get_dictionary_statistics(self.request.user)
        context.update(dictionary_statistics)
        context["diary_entry_count"] = Diary.objects.filter(
            user_id=self.request.user.id, language=self.request.user.language_learned
        ).count()

        with connection.cursor() as cursor:
            cursor.execute(
                """
                SELECT DISTINCT language_name
                FROM diary_diary
                JOIN dictionary_language ON dictionary_language.id = diary_diary.language_id
                WHERE diary_diary.user_id = %s
                UNION
                SELECT DISTINCT language_name
                FROM dictionary_words
                JOIN dictionary_language ON dictionary_language.id = dictionary_words.language_id
                WHERE dictionary_words.user_id = %s
                """,
                [self.request.user.id, self.request.user.id],
            )
            languages = [language[0] for language in cursor.fetchall()]
            context["languages"] = languages
        return context


class MyProfileEdit(LoginRequiredMixin, UpdateView):
    form_class = CustomUserChangeForm
    template_name = "authentication/my_profile_edit.html"
    success_url = reverse_lazy("my_profile")

    @logger.catch
    def get_object(self):
        return get_object_or_404(User, pk=self.request.user.pk)

my_dictionary/authentication/templates/authentication/change_password.html
{% extends "base.html" %}

{% block title%}
Смена пароля
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-4">Смена пароля</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}  
        <div class="container">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Старый пароль:</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.old_password}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Новый пароль</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.new_password1}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Подтвердите новый пароль</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.new_password2}}</div>
                    </div>
                    <hr>
                    
                    {% if form.errors %}
                    <div class="checkbox mb-3 error-list">
                        <label class="error-list">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                        {{form.non_field_errors}}
                        </label>
                    </div>                    
                    {% endif %}
                    <div class="row">
                        <div class="col-sm-12">
                            <button class="btn btn-info" type="submit">Сменить пароль</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/login.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
<link type="text/css" href="{% static 'authentication/css/styles.css' %}" rel="stylesheet" />
{% endblock %}

{% block title%}
Вход
{% endblock %}

{% block body%}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Авторизация</h1>
        <p class="col-lg-10 fs-4">Авторизованным пользователям доступны личный дневник и личный словарь с возможностью автоматического повторения слов.</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
            {% csrf_token %}
          <div class="form-floating mb-3">
            {{ form.username }}
            <label for="username">Имя пользователя</label>
          </div>
          <div class="form-floating mb-3">
            {{ form.password }}
            <label>Пароль</label>
          </div>
          {% include 'authentication/inc/_form_errors.html' %}
          <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
          <hr class="my-4">
          <small class="text-muted">Еще нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйтесь</a></small><br>
          <small class="text-muted">Забыли пароль? <a href="{% url 'reset_password' %}">Восстановите</a></small>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

my_dictionary/authentication/templates/authentication/my_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
Мой профиль
{% endblock %}

{% block body%}
<div class="container">
    <div class="main-body">
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            {% if request.user.avatar %}
                            <img src="{{request.user.avatar.url}}" alt="Admin" class="rounded-circle" width="150">
                            {% else %}
                            <img src="{% static 'common/images/anonymous.png' %}" alt="Admin" class="rounded-circle" width="150">
                            {% endif %}
                            <div class="mt-3">
                                <h4>{{request.user.first_name}} {{request.user.last_name}}</h4>
                                <p class="text-muted font-size-sm">Мои языки:
                                    {% for language in languages %}
                                    {{language}}
                                    {% endfor %}
                                </p>
                                <a class="btn btn-outline-primary non_underline" href="{% url 'dictionary' %}">Мой словарь</a>
                                <a class="btn btn-outline-primary non_underline" href="{% url 'my_diary' %}">Мой дневник</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                Всего слов:
                            </h6>
                            <span class="text-secondary">{{words_total_number}}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                Повторить сегодня
                            </h6>
                            <span class="text-secondary">{{words_for_today_number}}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                Выученные слова
                            </h6>
                            <span class="text-secondary">{{learned_words_number}}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                Записей в дневнике
                            </h6>
                            <span class="text-secondary">{{diary_entry_count}}</span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Имя</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.first_name}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Фамилия</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.last_name}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Пол</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.get_gender_display}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Имя пользователя</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.username}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.email}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Текущий язык</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">{{request.user.language_learned}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Обо мне</h6>
                            </div><div class="col-sm-9 text-secondary">{{request.user.about_me}}</div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="btn btn-info non_underline" href="{% url 'my_profile_edit' %}">Редактировать</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/my_profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
Редактирование профиля
{% endblock %}

{% block body%}
<div class="container">
    <h1 class="my-4">Редактирование профиля</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}  
        <div class="container  mx-24">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Аватар</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.avatar}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Имя</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.first_name}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Фамилия</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.last_name}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Пол</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.gender}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Имя пользователя</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.username}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Email</h6>
                        </div>
                        <div class="col-sm-9 text-secondary">{{form.email}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Текущий язык</h6>
                        </div><div class="col-sm-9 text-secondary">{{form.language_learned}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <h6 class="mb-0">Обо мне</h6>
                        </div><div class="col-sm-9 text-secondary">{{form.about_me}}</div>
                    </div>
                    <hr>
                    <div class="row">
                        <span>Для смены пароля перейдите по <a href="{% url 'password_change' %}">ссылке</a></span>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-12">
                            <button class="btn btn-info" type="submit">Сохранить</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/password_reset_confirm.html
{% extends "base.html" %}

{% block title%}
Сброс пароля
{% endblock %}

{% block body %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    {% if validlink %}
        <div class="row align-items-center g-lg-5 py-5">
          <div class="col-lg-7 text-center text-lg-start">
            <h1 class="display-4 fw-bold lh-1 mb-3">Сброс пароля</h1>
            <p class="col-lg-10 fs-4">Введите, подтвердите и не забудьте запомнить новый пароль.</p>
          </div>
          <div class="col-md-10 mx-auto col-lg-5">
            <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
                {% csrf_token %}
              <div class="form-floating mb-3">
                {{ form.new_password1 }}
                <label for="username">Введите новый пароль</label>
              </div>
              <div class="form-floating mb-3">
                {{ form.new_password2 }}
                <label>Подтвердите новый пароль</label>
              </div>
              {% include 'authentication/inc/_form_errors.html' %}
              <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
            </form>
          </div>
        </div>
    {% else %}
        <h1> Ошибка при смене пароля!!!</h1>
        <p> Ссылка на сброс пароля была недействительной, возможно, потому, что
        она уже использовалась. Пожалуйста, запросите новый сброс пароля.</p>
    {% endif %}
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/password_reset_done.html
{% extends "base.html" %}

{% block title%}
Сброс пароля
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="my-4">Сброс пароля</h1>
    <p>Мы отправили вам по электронной почте инструкции
        по установке пароля. Если они не получены в течение
        нескольких минут, то проверьте папку со спамом.
    </p>
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/password_reset_email.html
Для смены пароля пользователя с электронной почтой {{ email }} перейдите по ссылке ниже:
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

my_dictionary/authentication/templates/authentication/password_reset_form.html
{% extends "base.html" %}

{% block title%}
Сброс пароля
{% endblock %}

{% block body %}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Сброс пароля</h1>
        <p class="col-lg-10 fs-4">Введите e-mail, привязанный в вашему аккаунту.
            И мы отправим вам на электронную почту письмо со ссылкой на сброс пароля.</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
            {% csrf_token %}
          <div class="form-floating mb-3">
            {{form.email}}
            <label for="username">E-mail</label>
          </div>
          {% include 'authentication/inc/_form_errors.html' %}
          <button class="w-100 btn btn-lg btn-primary" type="submit">Сброс пароля</button>
          <hr class="my-4">
          <small class="text-muted">Еще нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйтесь</a></small><br>
          <small class="text-muted">Вспомнили пароль? <a href="{% url 'login' %}">Авторизуйтесь</a></small>
        </form>
      </div>
    </div>
</div>
{% endblock %}

my_dictionary/authentication/templates/authentication/register.html
{% extends 'base.html' %}
{% load static %}

{% block title%}
Регистрация
{% endblock %}

{% block body%}
<div class="container col-xl-10 col-xxl-8 px-4 py-5">
    <div class="row align-items-center g-lg-5 py-5">
      <div class="col-lg-7 text-center text-lg-start">
        <h1 class="display-4 fw-bold lh-1 mb-3">Регистрация</h1>
        <p class="col-lg-10 fs-4">Авторизованным пользователям доступны личный дневник и личный словарь с возможностью автоматического повторения слов.</p>
      </div>
      <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light" method="post">
            {% csrf_token %}
          <div class="form-floating mb-3">
            {{ form.username }}
            <label for="username">Имя пользователя</label>
          </div>
          <div class="form-floating mb-3">
            {{ form.first_name }}
            <label for="username">Имя</label>
          </div>
          <div class="form-floating mb-3">
            {{ form.password1 }}
            <label>Пароль</label>
          </div>
          <div class="form-floating mb-3">
            {{ form.password2 }}
            <label>Повторите пароль</label>
          </div>
            <p><label for="id_agreement">
                Принимаю условия
                <a href="{% url 'user_agreement'  %}">пользовательского соглашения</a>
                и даю согласие на
                <a href="{% url 'privacy_policy'  %}">обрбаботку персональных данных</a>
                </label>
                {{ form.agreement }}
            </p>
          {% if form.errors %}
          <div class="checkbox mb-3 error-list">
              <label class="error-list">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
              {{form.non_field_errors}}
            </label>
          </div>                    
          {% endif %}
          <button class="w-100 btn btn-lg btn-primary" type="submit">Регистрация</button>
          <hr class="my-4">
          <small class="text-muted">Уже есть аккаунт? <a href="{% url 'login' %}">Авторизуйтесь</a></small>
        </form>
      </div>
    </div>
  </div>
{% endblock %}